import path from 'node:path';

export const WIKI_DIR_NAME = '.code-wiki';
export const TEAM_DIR = 'team';
export const CACHE_DIR = 'cache';
export const MANIFEST_FILE = 'manifest.json';
export const PENDING_SYNC_FILE = 'pending-sync.json';

export const LANGUAGE_EXTENSIONS: Record<string, string> = {
  '.ts': 'typescript', '.tsx': 'typescript', '.js': 'typescript', '.jsx': 'typescript',
  '.py': 'python', '.pyi': 'python',
  '.go': 'go',
  '.java': 'java',
  '.rs': 'rust',
  '.rb': 'ruby',
};

export const IGNORED_DIRS = [
  'node_modules', '.git', 'dist', 'build', 'target', '__pycache__',
  '.next', '.nuxt', 'vendor', 'coverage', '.gradle', '.idea', '.vscode',
];

export const IGNORED_FILES = [
  '.env', '.env.local', '.env.production', '.env.test',
  'credentials.json', 'secrets.json', '.npmrc',
];

export const GENERATED_MARKERS = [
  'DO NOT EDIT', 'AUTO-GENERATED', '@generated', 'Code generated by',
];

export function wikiPaths(repoRoot: string) {
  const base = path.join(repoRoot, WIKI_DIR_NAME);
  return {
    base,
    team: path.join(base, TEAM_DIR),
    cache: path.join(base, CACHE_DIR),
    manifest: path.join(base, CACHE_DIR, MANIFEST_FILE),
    pendingSync: path.join(base, CACHE_DIR, PENDING_SYNC_FILE),
    modules: (layer: 'team' | 'cache') => path.join(base, layer, 'modules'),
    flows: (layer: 'team' | 'cache') => path.join(base, layer, 'flows'),
    graphs: path.join(base, CACHE_DIR, 'graphs'),
  };
}